"""empty message

Revision ID: 009fd79ce62e
Revises: ffdc0a98111c
Create Date: 2023-02-22 12:51:27.225811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009fd79ce62e'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backdrop_path', sa.String(length=1000), nullable=True),
    sa.Column('genre_ids', sa.String(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('overview', sa.String(length=5000), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('video', sa.Boolean(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('public_list', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.Column('watch_date', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_movies',
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], )
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('bio')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('list_movies')
    op.drop_table('reviews')
    op.drop_table('lists')
    op.drop_table('movies')
    # ### end Alembic commands ###