"""empty message

Revision ID: 34281f867fab
Revises: a436fc8a8e51
Create Date: 2023-05-05 23:45:38.070961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34281f867fab'
down_revision = 'a436fc8a8e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('location')

    # ### end Alembic commands ###